services:
  postgres:
    image: postgres:16
    container_name: document-service-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: document_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
