spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/document_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  batch-size: 50
  document:
    number-prefix: DOC
  transition:
    batch-size: 50
    max-concurrency: 4
  workers:
    submit:
      enabled: true
      interval: 10000
    approve:
      enabled: true
      interval: 15000
